language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - a.pueblah@alumnos.upm.es
    - apueblahol@gmail.com
script:
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.projectKey=alexph9_Alejandro.Puebla.Holguin.SVC.miw.upm.es -Dsonar.organization=alexph9-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR
